-- MySQL Script generated by MySQL Workbench
-- 11/13/19 16:19:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bdBodega
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdBodega
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdBodega` DEFAULT CHARACTER SET utf8 COLLATE utf8_spanish2_ci ;
USE `bdBodega` ;

-- -----------------------------------------------------
-- Table `bdBodega`.`Tb_Bodega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdBodega`.`Tb_Bodega` (
  `Codigo_p` INT NOT NULL,
  `Tipo_p` VARCHAR(16) NULL,
  `Descri` VARCHAR(30) NULL,
  `FechaR2` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Cant` INT(2) NULL,
  `Stop` INT(2) NULL,
  `Precio` DECIMAL(10,4) NULL,
  `PUni` DECIMAL(10,4) NULL,
  `PVent` DECIMAL(10,4) NULL,
  `UtilInicial` DECIMAL(10,4) NULL,
  `UtilBodega` DECIMAL(10,4) NULL,
  PRIMARY KEY (`Codigo_p`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdBodega`.`Tb_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdBodega`.`Tb_Usuarios` (
  `idUsuarios` INT NOT NULL,
  `Nombre` VARCHAR(25) NULL,
  `Password` VARCHAR(45) NULL,
  `Tipo_U` TINYINT(1) NULL,
  PRIMARY KEY (`idUsuarios`),
  UNIQUE INDEX `idUsuarios_UNIQUE` (`idUsuarios` ASC))
ENGINE = InnoDB;

INSERT INTO `Tb_Usuarios` (`idUsuarios`, `Nombre`, `Password`, `Tipo_U`) VALUES
('1', 'Jose', '#jose2016A', '1');
-- -----------------------------------------------------
-- Table `bdBodega`.`tb_Empl`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdBodega`.`tb_Empl` (
  `Codigo` INT NOT NULL,
  `CantVent` INT(2) NULL,
  `Correo` VARCHAR(30) NULL,
  `Tel` VARCHAR(10) NULL,
  `Nombre` VARCHAR(20) NULL,
  `Ident` INT(10) NULL,
  `Cargo` VARCHAR(25) NULL,
  `SuelB` DECIMAL(10,4) NULL,
  `FechaR3` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `IdUsuario` INT NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `fk_tb_Empl_Tb_Usuarios1_idx` (`IdUsuario` ASC),
  CONSTRAINT `fk_tb_Empl_Tb_Usuarios1`
    FOREIGN KEY (`IdUsuario`)
    REFERENCES `bdBodega`.`Tb_Usuarios` (`idUsuarios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdBodega`.`Tb_Entrega`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdBodega`.`Tb_Entrega` (
  `Vendedor` VARCHAR(25) NULL,
  `TipoP` VARCHAR(25) NULL,
  `Descr` VARCHAR(25) NULL,
  `Stop` INT(2) NULL,
  `Codigo` INT NOT NULL,
  `Precio` DECIMAL(10,4) NULL,
  `Promo` TINYINT(1) NULL,
  `FechaR` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Codigo_C` INT NOT NULL,
  `Codigo_emp` INT NOT NULL,
  PRIMARY KEY (`Codigo`),
  INDEX `fk_Tb_Produc_Tb_Bodega_idx` (`Codigo_C` ASC),
  INDEX `fk_Tb_Produc_tb_Empl1_idx` (`Codigo_emp` ASC),
  CONSTRAINT `fk_Tb_Produc_Tb_Bodega`
    FOREIGN KEY (`Codigo_C`)
    REFERENCES `bdBodega`.`Tb_Bodega` (`Codigo_p`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_Produc_tb_Empl1`
    FOREIGN KEY (`Codigo_emp`)
    REFERENCES `bdBodega`.`tb_Empl` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdBodega`.`Tb_Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdBodega`.`Tb_Clientes` (
  `IDclie` INT NOT NULL,
  `Nombre` VARCHAR(25) NULL,
  `Direc` VARCHAR(25) NULL,
  `Tele` VARCHAR(10) NULL,
  `TipoP` VARCHAR(25) NULL,
  `FormaP` VARCHAR(15) NULL,
  `Cant` INT(2) NULL,
  `Valorini` DECIMAL(10,4) NULL,
  `Deuda` DECIMAL(10,4) NULL,
  `ValoCut` DECIMAL(10,4) NULL,
  `Fecha` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `Codigo_E1` INT NOT NULL,
  PRIMARY KEY (`IDclie`),
  INDEX `fk_Tb_Clientes_tb_Empl1_idx` (`Codigo_E1` ASC),
  CONSTRAINT `fk_Tb_Clientes_tb_Empl1`
    FOREIGN KEY (`Codigo_E1`)
    REFERENCES `bdBodega`.`tb_Empl` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdBodega`.`Tb_Compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdBodega`.`Tb_Compras` (
  `IDventas` INT NOT NULL AUTO_INCREMENT,
  `NombreEmpl` VARCHAR(25) NULL,
  `NombreClien` VARCHAR(25) NULL,
  `Codigo_E` INT NOT NULL,
  `IDclie1` INT NOT NULL,
  `Codigo_en1` INT NOT NULL,
  PRIMARY KEY (`IDventas`),
  INDEX `fk_Tb_Ventas_tb_Empl1_idx` (`Codigo_E` ASC),
  INDEX `fk_Tb_Ventas_Tb_Clientes1_idx` (`IDclie1` ASC),
  INDEX `fk_Tb_Ventas_Tb_Entrega1_idx` (`Codigo_en1` ASC),
  CONSTRAINT `fk_Tb_Ventas_tb_Empl1`
    FOREIGN KEY (`Codigo_E`)
    REFERENCES `bdBodega`.`tb_Empl` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_Ventas_Tb_Clientes1`
    FOREIGN KEY (`IDclie1`)
    REFERENCES `bdBodega`.`Tb_Clientes` (`IDclie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tb_Ventas_Tb_Entrega1`
    FOREIGN KEY (`Codigo_en1`)
    REFERENCES `bdBodega`.`Tb_Entrega` (`Codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
